"use client";

import { useEffect, useMemo, useState } from "react";
import type { MailSettings, QualityAlert, QualityRule, QualityRun } from "@/lib/product/types";

type QualitySummaryResponse = {
  summary: {
    rules: QualityRule[];
    runs: QualityRun[];
    alerts: QualityAlert[];
    mail: MailSettings;
    adapters: Array<{
      tool: string;
      status: string;
      validation: string;
    }>;
    charts: {
      validation: {
        pass: number;
        warn: number;
        fail: number;
      };
      severity: Record<"SEV-1" | "SEV-2" | "SEV-3" | "SEV-4", number>;
    };
  };
};

const sections = ["Overview", "Rules", "Alerts"] as const;
const ruleFrequencies = ["Hourly", "Daily", "Before refresh", "After refresh"] as const;

function RuleComposerModal({
  onClose,
  onDraft,
}: {
  onClose: () => void;
  onDraft: (prompt: string, mode: "natural_language" | "statement", frequency: string) => Promise<{ title: string; generatedBy: string } | null>;
}) {
  const [rulePrompt, setRulePrompt]   = useState("");
  const [ruleMode, setRuleMode]       = useState<"natural_language" | "statement">("natural_language");
  const [ruleFrequency, setFrequency] = useState<(typeof ruleFrequencies)[number]>("Hourly");
  const [phase, setPhase] = useState<"idle" | "generating" | "done">("idle");
  const [result, setResult] = useState<{ title: string; generatedBy: string } | null>(null);

  async function handleDraft() {
    if (!rulePrompt.trim()) return;
    setPhase("generating");
    const res = await onDraft(rulePrompt, ruleMode, ruleFrequency);
    setResult(res);
    setPhase("done");
    // Auto-close after showing the success state
    setTimeout(onClose, 2200);
  }

  const isDone = phase === "done";
  const isGenerating = phase === "generating";
  const isLlm = result !== null && result?.generatedBy !== "heuristic";

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget && phase === "idle") onClose(); }}
    >
      {isDone ? (
        <div className="w-full max-w-lg rounded-[28px] border border-slate-200 bg-white p-8 shadow-[0_24px_64px_rgba(15,23,42,0.12)] text-center">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-emerald-100 bg-emerald-50">
            <svg viewBox="0 0 24 24" className="h-7 w-7 text-emerald-500" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M20 6 9 17l-5-5" />
            </svg>
          </div>
          <p className="mt-4 text-lg font-semibold text-slate-950">Rule drafted</p>
          <p className="mt-1.5 text-sm text-slate-500 max-w-xs mx-auto">{result?.title ?? rulePrompt.slice(0, 72)}</p>
          <div className="mt-4 inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-medium text-slate-500">
            <span className={`h-1.5 w-1.5 rounded-full ${isLlm ? "bg-cyan-400" : "bg-slate-400"}`} />
            {isLlm
              ? `Generated by ${result?.generatedBy ?? "model"}`
              : "Generated by heuristic fallback"}
          </div>
          <p className="mt-5 text-xs text-slate-400">Review it in the Rules library and approve when ready.</p>
        </div>
      ) : (
        <div className="w-full max-w-lg rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_24px_64px_rgba(15,23,42,0.12)]">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <p className="text-base font-semibold text-slate-950">New quality rule</p>
              <p className="mt-0.5 text-sm text-slate-400">Describe what to check in plain English or as a statement</p>
            </div>
            <button type="button" onClick={onClose} disabled={isGenerating} className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700 disabled:opacity-30">
              <svg viewBox="0 0 20 20" className="h-4 w-4" fill="currentColor"><path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z" /></svg>
            </button>
          </div>

          <div className="flex flex-wrap gap-2">
            <SectionButton active={ruleMode === "natural_language"} onClick={() => setRuleMode("natural_language")}>
              Natural language
            </SectionButton>
            <SectionButton active={ruleMode === "statement"} onClick={() => setRuleMode("statement")}>
              Write statement
            </SectionButton>
          </div>

          <label className="mt-4 block">
            <span className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Frequency</span>
            <select
              className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none"
              value={ruleFrequency}
              onChange={(e) => setFrequency(e.target.value as (typeof ruleFrequencies)[number])}
            >
              {ruleFrequencies.map((f) => <option key={f}>{f}</option>)}
            </select>
          </label>

          <textarea
            className="mt-4 min-h-[120px] w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-700 outline-none disabled:opacity-50"
            placeholder={
              ruleMode === "statement"
                ? "Write the rule statement"
                : "Describe the rule"
            }
            value={rulePrompt}
            onChange={(e) => setRulePrompt(e.target.value)}
            disabled={isGenerating}
            autoFocus
          />

          {isGenerating && (
            <div className="mt-3 flex items-center gap-2 text-xs text-slate-400">
              <svg className="h-3.5 w-3.5 animate-spin text-indigo-500" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8v4a4 4 0 0 0-4 4H4Z" />
              </svg>
              Running model and building rule structure…
            </div>
          )}

          <div className="mt-4 flex gap-2">
            <button
              type="button"
              onClick={() => void handleDraft()}
              disabled={isGenerating || !rulePrompt.trim()}
              className="inline-flex items-center gap-2 rounded-full border border-slate-900 bg-slate-900 px-5 py-2 text-sm font-medium text-white disabled:opacity-40"
            >
              {isGenerating && (
                <svg className="h-3.5 w-3.5 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 0 1 8-8v4a4 4 0 0 0-4 4H4Z" />
                </svg>
              )}
              {isGenerating ? "Generating…" : "Generate draft"}
            </button>
            <button
              type="button"
              onClick={onClose}
              disabled={isGenerating}
              className="rounded-full border border-slate-200 bg-white px-5 py-2 text-sm font-medium text-slate-600 disabled:opacity-40"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
const severityLevels = ["SEV-1", "SEV-2", "SEV-3", "SEV-4"] as const;

function severityCard(_severity: string) {
  return "bg-white border-slate-200";
}

function severityBadge(severity: string) {
  if (severity === "SEV-1") return "border-rose-200 bg-rose-50 text-rose-700";
  if (severity === "SEV-2") return "border-orange-200 bg-orange-50 text-orange-700";
  if (severity === "SEV-3") return "border-amber-200 bg-amber-50 text-amber-700";
  return "border-slate-200 bg-slate-100 text-slate-500";
}


function severityDot(severity: string) {
  if (severity === "SEV-1") return "bg-rose-400";
  if (severity === "SEV-2") return "bg-orange-400";
  if (severity === "SEV-3") return "bg-amber-400";
  return "bg-slate-400";
}

function statusBadge(status: string) {
  if (status === "fail") return "border-rose-200 bg-rose-50 text-rose-700";
  if (status === "warn") return "border-amber-200 bg-amber-50 text-amber-700";
  return "border-emerald-100 bg-emerald-50 text-emerald-700";
}

function ruleStatusDot(status: string) {
  if (status === "approved") return "bg-emerald-400";
  if (status === "draft") return "bg-amber-400";
  if (status === "disabled") return "bg-slate-300";
  return "bg-slate-300";
}

function sourceLabel(ruleId: string) {
  if (ruleId.startsWith("watchdog-")) return "Watchdog";
  if (ruleId.startsWith("generated-")) return "Generated";
  if (ruleId.startsWith("system-")) return "System";
  return "Custom";
}

function formatTimestamp(value?: string) {
  if (!value) return "Unknown";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Unknown";
  return date.toLocaleString([], {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function ruleCommandPreview(rule?: QualityRule) {
  return (
    (rule?.generatedDsl.commandPreview as string | undefined) ??
    rule?.draft.generatedSql ??
    rule?.draft.generatedScript ??
    "Command preview unavailable"
  );
}

function ruleFrequencyLabel(rule?: QualityRule) {
  return rule?.frequency ?? "Hourly";
}

function normalizeEvidenceLine(line: string) {
  const trimmed = line.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("Executed SQL:")) return null;
  if (/^\{.*\}$/.test(trimmed)) return "Structured log event captured during this run.";
  if (trimmed.length > 220) return `${trimmed.slice(0, 217).trimEnd()}...`;
  return trimmed;
}

function summarizeEvidence(evidence: string[]) {
  const normalized = evidence
    .map(normalizeEvidenceLine)
    .filter((line): line is string => Boolean(line));

  if (!normalized.length) {
    return ["Execution summary available in the command preview."];
  }

  return Array.from(new Set(normalized)).slice(0, 3);
}

function DonutStat({
  label,
  value,
  total,
  colorClass,
}: {
  label: string;
  value: number;
  total: number;
  colorClass: string;
}) {
  const radius = 30;
  const circumference = 2 * Math.PI * radius;
  const percent = total ? Math.round((value / total) * 100) : 0;
  const dashoffset = circumference - (percent / 100) * circumference;

  return (
    <div className="rounded-[26px] border border-slate-200 bg-white p-5">
      <div className="flex items-center gap-4">
        <div className="relative h-[88px] w-[88px] shrink-0">
          <svg viewBox="0 0 88 88" className="h-[88px] w-[88px] -rotate-90">
            <circle cx="44" cy="44" r={radius} fill="none" stroke="#e2e8f0" strokeWidth="8" />
            <circle
              cx="44"
              cy="44"
              r={radius}
              fill="none"
              stroke="currentColor"
              strokeWidth="8"
              strokeLinecap="round"
              strokeDasharray={circumference}
              strokeDashoffset={dashoffset}
              className={colorClass}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-lg font-semibold text-slate-900">{percent}%</span>
            <span className="text-[10px] uppercase tracking-[0.18em] text-slate-400">share</span>
          </div>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">{label}</p>
          <p className="mt-1 text-2xl font-semibold text-slate-950">{value}</p>
          <p className="mt-1 text-sm text-slate-500">
            {value} of {Math.max(total, 1)} active runs
          </p>
        </div>
      </div>
    </div>
  );
}

function SectionButton({
  active,
  children,
  onClick,
}: {
  active: boolean;
  children: React.ReactNode;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`rounded-full border px-4 py-2 text-sm font-medium transition ${
        active
          ? "border-slate-900 bg-slate-900 text-white"
          : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:text-slate-900"
      }`}
    >
      {children}
    </button>
  );
}

function StatCard({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div className="rounded-[26px] border border-slate-200 bg-white p-5">
      <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">{label}</p>
      <p className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-slate-950">{value}</p>
      <p className="mt-2 text-sm text-slate-500">{hint}</p>
    </div>
  );
}

function EmptyPanel({ text }: { text: string }) {
  return (
    <div className="rounded-[26px] border border-dashed border-slate-200 bg-white p-6 text-sm text-slate-500">
      {text}
    </div>
  );
}

function MailIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
      className="h-[18px] w-[18px]"
      fill="currentColor"
    >
      <path d="M20 4H4c-1.1 0-2 .9-2 2l.01 12C2.01 19.1 2.9 20 4 20H20c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2m0 4-8 5-8-5V6l8 5 8-5z" />
    </svg>
  );
}

function GearIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-[16px] w-[16px]" fill="currentColor">
      <path d="M19.14 12.94c.04-.31.06-.63.06-.94s-.02-.63-.06-.94l2.03-1.58a.5.5 0 0 0 .12-.64l-1.92-3.32a.5.5 0 0 0-.6-.22l-2.39.96a7.2 7.2 0 0 0-1.63-.94l-.36-2.54a.5.5 0 0 0-.49-.42h-3.84a.5.5 0 0 0-.49.42l-.36 2.54c-.58.22-1.12.53-1.63.94l-2.39-.96a.5.5 0 0 0-.6.22L2.71 8.84a.5.5 0 0 0 .12.64l2.03 1.58c-.04.31-.06.63-.06.94s.02.63.06.94l-2.03 1.58a.5.5 0 0 0-.12.64l1.92 3.32c.13.22.39.31.6.22l2.39-.96c.51.4 1.05.72 1.63.94l.36 2.54c.04.24.25.42.49.42h3.84c.24 0 .45-.18.49-.42l.36-2.54c.58-.22 1.12-.53 1.63-.94l2.39.96c.22.09.47 0 .6-.22l1.92-3.32a.5.5 0 0 0-.12-.64l-2.03-1.58ZM12 15.5A3.5 3.5 0 1 1 12 8a3.5 3.5 0 0 1 0 7.5Z" />
    </svg>
  );
}

export function QualityConsole({
  initialSection = "Overview",
  onRemedyAlert,
  showSectionTabs = true,
  showHeader = true,
}: {
  initialSection?: (typeof sections)[number];
  onRemedyAlert?: (alert: QualityAlert, rule?: QualityRule) => void;
  showSectionTabs?: boolean;
  showHeader?: boolean;
}) {
  const [activeSection, setActiveSection] = useState<(typeof sections)[number]>(initialSection);
  const [activeTool, setActiveTool] = useState<string>("All tools");
  const [summary, setSummary] = useState<QualitySummaryResponse["summary"] | null>(null);
  const [showRuleComposer, setShowRuleComposer] = useState(false);
  const [ruleView, setRuleView] = useState<"library" | "detail">(
    initialSection === "Rules" ? "library" : "detail"
  );
  const [selectedRuleId, setSelectedRuleId] = useState<string | null>(null);
  const [ruleMenuOpenId, setRuleMenuOpenId] = useState<string | null>(null);
  const [mailForm, setMailForm] = useState({
    host: "",
    port: "587",
    username: "",
    sender: "",
    enabled: false,
  });
  const [recipientPolicies, setRecipientPolicies] = useState<MailSettings["recipients"]>([]);
  const [recipientDraft, setRecipientDraft] = useState("");
  const [recipientSeverity, setRecipientSeverity] =
    useState<MailSettings["recipients"][number]["notifyAtOrAbove"]>("SEV-2");
  const [showMailModal, setShowMailModal] = useState(false);

  useEffect(() => {
    void loadSummary();
  }, []);

  useEffect(() => {
    setActiveSection(initialSection);
    if (initialSection === "Rules") {
      setRuleView("library");
    }
  }, [initialSection]);

  async function loadSummary() {
    const response = await fetch("/api/quality/summary");
    const data = (await response.json()) as QualitySummaryResponse;
    setSummary(data.summary);
    setMailForm({
      host: data.summary.mail.host ?? "",
      port: String(data.summary.mail.port ?? 587),
      username: data.summary.mail.username ?? "",
      sender: data.summary.mail.sender ?? "",
      enabled: Boolean(data.summary.mail.enabled),
    });
    setRecipientPolicies(data.summary.mail.recipients ?? []);
  }

  async function draftRule(
    rulePrompt: string,
    ruleMode: "natural_language" | "statement",
    ruleFrequency: string,
  ): Promise<{ title: string; generatedBy: string } | null> {
    const prompt =
      ruleMode === "statement"
        ? `Create a quality rule from this explicit statement.\nStatement: ${rulePrompt}\nFrequency: ${ruleFrequency}`
        : `Create a quality rule from this natural-language request.\nRequest: ${rulePrompt}\nFrequency: ${ruleFrequency}`;

    const res = await fetch("/api/quality/rules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt, title: rulePrompt.slice(0, 72) }),
    });

    if (res.ok) {
      const data = (await res.json()) as { rule?: { title?: string }; generatedBy?: string };
      const generatedBy = data.generatedBy ?? "heuristic";
      const title = data.rule?.title ?? rulePrompt.slice(0, 48);
      await loadSummary();
      return { title, generatedBy };
    }

    await loadSummary();
    return null;
  }

  async function approveRule(ruleId: string) {
    await fetch("/api/quality/rules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ approveRuleId: ruleId }),
    });
    await loadSummary();
  }

  async function updateRule(
    ruleId: string,
    updates: Partial<Pick<QualityRule, "status" | "frequency">>
  ) {
    // Optimistic update — apply immediately so the button label and status badge
    // change without waiting for the server round-trip
    setSummary((prev) =>
      prev
        ? { ...prev, rules: prev.rules.map((r) => (r.ruleId === ruleId ? { ...r, ...updates } : r)) }
        : prev
    );
    setRuleMenuOpenId(null);

    await fetch("/api/quality/rules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ updateRuleId: ruleId, ...updates }),
    });
    await loadSummary();
  }

  async function deleteRule(ruleId: string) {
    await fetch("/api/quality/rules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ deleteRuleId: ruleId }),
    });
    setRuleMenuOpenId(null);
    if (selectedRuleId === ruleId) {
      setRuleView("library");
      setSelectedRuleId(null);
    }
    await loadSummary();
  }

  async function saveMail() {
    await fetch("/api/quality/mail", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...mailForm,
        port: Number(mailForm.port),
        recipients: recipientPolicies,
      }),
    });
    await loadSummary();
  }

  function addRecipientPolicy() {
    const recipient = recipientDraft.trim();
    if (!recipient) return;
    setRecipientPolicies((current) => {
      const next = current.filter((item) => item.recipient.toLowerCase() !== recipient.toLowerCase());
      return [...next, { recipient, notifyAtOrAbove: recipientSeverity }];
    });
    setRecipientDraft("");
  }

  function removeRecipientPolicy(recipient: string) {
    setRecipientPolicies((current) => current.filter((item) => item.recipient !== recipient));
  }

  function updateRecipientPolicy(
    recipient: string,
    notifyAtOrAbove: MailSettings["recipients"][number]["notifyAtOrAbove"]
  ) {
    setRecipientPolicies((current) =>
      current.map((item) =>
        item.recipient === recipient ? { ...item, notifyAtOrAbove } : item
      )
    );
  }

  const toolTabs = useMemo(() => {
    const tools = Array.from(new Set((summary?.rules ?? []).map((rule) => rule.tool))).sort();
    return ["All tools", ...tools];
  }, [summary]);

  useEffect(() => {
    if (!toolTabs.includes(activeTool)) {
      setActiveTool("All tools");
    }
  }, [activeTool, toolTabs]);

  const filteredRules = useMemo(
    () =>
      (summary?.rules ?? []).filter((rule) =>
        activeTool === "All tools" ? true : rule.tool === activeTool
      ),
    [activeTool, summary]
  );

  const filteredRuns = useMemo(
    () =>
      (summary?.runs ?? []).filter((run) => {
        if (activeTool === "All tools") return true;
        return summary?.rules.find((rule) => rule.ruleId === run.ruleId)?.tool === activeTool;
      }),
    [activeTool, summary]
  );

  const filteredAlerts = useMemo(() => {
    const all = (summary?.alerts ?? []).filter((alert) => {
      if (activeTool === "All tools") return true;
      return summary?.rules.find((rule) => rule.ruleId === alert.ruleId)?.tool === activeTool;
    });
    // One alert per ruleId — latest wins
    const latestByRule = new Map<string, typeof all[number]>();
    for (const alert of all) {
      const existing = latestByRule.get(alert.ruleId);
      if (!existing || alert.createdAt > existing.createdAt) {
        latestByRule.set(alert.ruleId, alert);
      }
    }
    return [...latestByRule.values()];
  }, [activeTool, summary]);

  useEffect(() => {
    if (!filteredRules.length) {
      setSelectedRuleId(null);
      return;
    }

    const nextRuleId =
      selectedRuleId && filteredRules.some((rule) => rule.ruleId === selectedRuleId)
        ? selectedRuleId
        : filteredRules[0].ruleId;
    setSelectedRuleId(nextRuleId);
  }, [filteredRules, selectedRuleId]);

  const selectedRule = useMemo(
    () => filteredRules.find((rule) => rule.ruleId === selectedRuleId) ?? null,
    [filteredRules, selectedRuleId]
  );

  const selectedRuleRuns = useMemo(
    () => filteredRuns.filter((run) => run.ruleId === selectedRule?.ruleId),
    [filteredRuns, selectedRule]
  );

  const severityOrder = { "SEV-1": 4, "SEV-2": 3, "SEV-3": 2, "SEV-4": 1 };
  const openAlerts = useMemo(
    () => filteredAlerts.filter((alert) => alert.status === "open").slice(0, 4),
    [filteredAlerts]
  );

  const passCount = filteredRuns.filter((run) => run.status === "pass").length;
  const warnCount = filteredRuns.filter((run) => run.status === "warn").length;
  const failCount = filteredRuns.filter((run) => run.status === "fail").length;
  const validationTotal = passCount + warnCount + failCount;

  const sourceCounts = {
    system: filteredRules.filter((rule) => rule.ruleId.startsWith("system-")).length,
    generated: filteredRules.filter((rule) => rule.ruleId.startsWith("generated-")).length,
    watchdog: filteredRules.filter((rule) => rule.ruleId.startsWith("watchdog-")).length,
    custom: filteredRules.filter(
      (rule) =>
        !rule.ruleId.startsWith("system-") &&
        !rule.ruleId.startsWith("generated-") &&
        !rule.ruleId.startsWith("watchdog-")
    ).length,
  };

  return (
    <div className="space-y-6">
      <div className="rounded-[28px] border border-slate-200 bg-white p-5">
        {showHeader || showSectionTabs ? (
          <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
            {showHeader ? (
              <div>
                <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">
                  Quality ops
                </p>
                <h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-slate-950">
                  Checks, runs, and alerts
                </h2>
                <p className="mt-2 max-w-2xl text-sm text-slate-500">
                  Review rule health, run history, and the signals that matter for{" "}
                  {activeTool === "All tools" ? "your workspace" : activeTool}.
                </p>
              </div>
            ) : (
              <div />
            )}

            {showSectionTabs ? (
              <div className="flex flex-wrap gap-2">
                {sections.map((section) => (
                  <SectionButton
                    key={section}
                    active={activeSection === section}
                    onClick={() => setActiveSection(section)}
                  >
                    {section}
                  </SectionButton>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {showSectionTabs ? (
          <div className={`${showHeader || showSectionTabs ? "mt-5 " : ""}flex flex-wrap gap-2`}>
            {toolTabs.map((tool) => (
              <SectionButton
                key={tool}
                active={activeTool === tool}
                onClick={() => setActiveTool(tool)}
              >
                {tool}
              </SectionButton>
            ))}
          </div>
        ) : (
          <div className={`${showHeader ? "mt-5 " : ""}flex items-start justify-between gap-4`}>
            <div className="inline-flex max-w-full items-center gap-1 overflow-x-auto rounded-[18px] border border-slate-200 bg-slate-50 p-1">
              {toolTabs.map((tool) => (
                <button
                  key={tool}
                  type="button"
                  onClick={() => setActiveTool(tool)}
                  className={`shrink-0 rounded-[14px] px-3 py-2 text-xs font-medium transition ${
                    activeTool === tool
                      ? "bg-white text-slate-950 shadow-sm"
                      : "text-slate-500 hover:text-slate-900"
                  }`}
                >
                  {tool}
                </button>
              ))}
            </div>

            {initialSection === "Rules" ? (
              <button
                type="button"
                onClick={() => setShowRuleComposer((current) => !current)}
                className="inline-flex shrink-0 items-center gap-2 rounded-full border border-indigo-600 bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition hover:brightness-[0.98]"
              >
                <span className="material-symbols-rounded text-[18px] leading-none">add</span>
                <span>New rule</span>
              </button>
            ) : initialSection === "Alerts" ? (
              <button
                type="button"
                onClick={() => setShowMailModal(true)}
                className="relative flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-[rgba(124,58,237,0.18)] bg-[rgba(124,58,237,0.08)] text-[#7c3aed] transition hover:border-[rgba(124,58,237,0.28)] hover:bg-[rgba(124,58,237,0.12)] hover:text-[#6d28d9]"
                aria-label="Configure email notifications"
                title="Configure email notifications"
              >
                <MailIcon />
              </button>
            ) : null}
          </div>
        )}
      </div>

      {activeSection === "Overview" ? (
        <div className="space-y-6">
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <StatCard
              label="Active checks"
              value={String(filteredRules.length)}
              hint="Rules currently in scope"
            />
            <StatCard
              label="Rule runs"
              value={String(filteredRuns.length)}
              hint="Recent execution history"
            />
            <StatCard
              label="Open alerts"
              value={String(openAlerts.length)}
              hint="Alerts requiring attention"
            />
            <StatCard
              label="Signal mix"
              value={`${sourceCounts.system + sourceCounts.watchdog}/${Math.max(filteredRules.length, 1)}`}
              hint="System and watchdog rules in the current pack"
            />
          </div>

          <div className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,0.9fr)]">
            <div className="grid gap-4 lg:grid-cols-3">
              <DonutStat
                label="Passing checks"
                value={passCount}
                total={validationTotal}
                colorClass="text-emerald-500"
              />
              <DonutStat
                label="Warnings"
                value={warnCount}
                total={validationTotal}
                colorClass="text-amber-500"
              />
              <DonutStat
                label="Failures"
                value={failCount}
                total={validationTotal}
                colorClass="text-rose-500"
              />
            </div>

            <div className="rounded-[26px] border border-slate-200 bg-white p-5">
              <p className="text-lg font-semibold text-slate-950">Open alerts</p>
              <p className="mt-1 text-sm text-slate-500">Current issues requiring follow-up</p>
              <div className="mt-4 space-y-3">
                {openAlerts.length ? (
                  openAlerts.map((alert) => (
                    <div
                      key={alert.alertId}
                      className="rounded-2xl border border-slate-200 bg-slate-50 p-4"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <p className="text-sm font-semibold text-slate-900">{alert.title}</p>
                        <span
                          className={`rounded-full border px-2.5 py-1 text-[11px] font-medium ${severityBadge(
                            alert.severity
                          )}`}
                        >
                          {alert.severity}
                        </span>
                      </div>
                      <p className="mt-2 text-sm text-slate-500">{alert.detail}</p>
                    </div>
                  ))
                ) : (
                  <EmptyPanel text="No active alerts right now." />
                )}
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {activeSection === "Rules" ? (
        <div className="space-y-4">
          {ruleView === "library" ? (
            <div className="rounded-[26px] border border-slate-200 bg-white p-4">
              <div className="mb-5 flex flex-wrap items-start justify-between gap-4">
                <div>
                  <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Rule library</p>
                  <p className="mt-1.5 text-xl font-semibold tracking-[-0.03em] text-slate-950">
                    {filteredRules.length} checks in scope
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  {sourceCounts.system > 0 && (
                    <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600">
                      <span className="h-1.5 w-1.5 rounded-full bg-indigo-400" />
                      {sourceCounts.system} system
                    </span>
                  )}
                  {sourceCounts.watchdog > 0 && (
                    <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600">
                      <span className="h-1.5 w-1.5 rounded-full bg-violet-400" />
                      {sourceCounts.watchdog} watchdog
                    </span>
                  )}
                  {sourceCounts.generated > 0 && (
                    <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600">
                      <span className="h-1.5 w-1.5 rounded-full bg-cyan-400" />
                      {sourceCounts.generated} generated
                    </span>
                  )}
                  {sourceCounts.custom > 0 && (
                    <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600">
                      <span className="h-1.5 w-1.5 rounded-full bg-slate-400" />
                      {sourceCounts.custom} custom
                    </span>
                  )}
                </div>
              </div>

              {showRuleComposer && (
                <RuleComposerModal
                  onClose={() => setShowRuleComposer(false)}
                  onDraft={draftRule}
                />
              )}

              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                {filteredRules.length ? (
                  filteredRules
                    .slice()
                    .sort((a, b) => severityOrder[b.severity] - severityOrder[a.severity])
                    .map((rule) => (
                      <div
                        key={rule.ruleId}
                        className={`relative rounded-2xl border px-4 py-4 text-slate-800 transition hover:shadow-sm ${severityCard(rule.severity)}`}
                      >
                        <div className="flex items-start justify-between gap-3">
                          <button
                            type="button"
                            onClick={() => {
                              setSelectedRuleId(rule.ruleId);
                              setRuleView("detail");
                            }}
                            className="min-w-0 flex-1 text-left"
                          >
                            <div className="flex items-center gap-2 mb-1">
                              <span className={`h-2 w-2 rounded-full shrink-0 ${ruleStatusDot(rule.status)}`} />
                              <p className="text-sm font-semibold text-slate-900 leading-snug">{rule.title}</p>
                            </div>
                            <p className="mt-1 text-xs text-slate-500 pl-4">
                              {rule.tool} · {sourceLabel(rule.ruleId)} · {ruleFrequencyLabel(rule)}
                            </p>
                          </button>
                          <div className="flex items-center gap-2 shrink-0">
                            <span
                              className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${severityBadge(
                                rule.severity
                              )}`}
                            >
                              {rule.severity}
                            </span>
                            {/* Inline pause/resume toggle */}
                            <button
                              type="button"
                              title={rule.status === "disabled" ? "Resume rule" : "Pause rule"}
                              onClick={(e) => {
                                e.stopPropagation();
                                void updateRule(rule.ruleId, {
                                  status: rule.status === "disabled" ? "approved" : "disabled",
                                });
                              }}
                              className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 transition-colors duration-200 focus:outline-none ${
                                rule.status === "disabled"
                                  ? "border-slate-200 bg-slate-200"
                                  : "border-indigo-500 bg-indigo-500"
                              }`}
                            >
                              <span
                                className={`inline-block h-4 w-4 transform rounded-full bg-white shadow transition-transform duration-200 ${
                                  rule.status === "disabled" ? "translate-x-0" : "translate-x-4"
                                }`}
                              />
                            </button>
                            <div className="relative">
                              <button
                                type="button"
                                onClick={() =>
                                  setRuleMenuOpenId((current) =>
                                    current === rule.ruleId ? null : rule.ruleId
                                  )
                                }
                                className="rounded-full border border-slate-200 bg-white/80 p-2 text-slate-400 transition hover:border-slate-300 hover:text-slate-700"
                                aria-label={`Manage ${rule.title}`}
                              >
                                <GearIcon />
                              </button>
                              {ruleMenuOpenId === rule.ruleId ? (
                                <div className="absolute right-0 top-12 z-20 w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_16px_40px_rgba(15,23,42,0.1)]">
                                  <p className="px-3 py-2 text-[11px] font-medium uppercase tracking-[0.18em] text-slate-400">
                                    Frequency
                                  </p>
                                  <div className="space-y-1">
                                    {ruleFrequencies.map((frequency) => (
                                      <button
                                        key={frequency}
                                        type="button"
                                        onClick={() => void updateRule(rule.ruleId, { frequency })}
                                        className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-sm transition ${
                                          ruleFrequencyLabel(rule) === frequency
                                            ? "bg-[#1e1e2e] text-white"
                                            : "text-slate-600 hover:bg-slate-50 hover:text-slate-950"
                                        }`}
                                      >
                                        <span>{frequency}</span>
                                      </button>
                                    ))}
                                  </div>
                                  <div className="my-2 h-px bg-slate-100" />
                                  <button
                                    type="button"
                                    onClick={() =>
                                      void updateRule(rule.ruleId, {
                                        status: rule.status === "disabled" ? "approved" : "disabled",
                                      })
                                    }
                                    className="flex w-full rounded-xl px-3 py-2 text-sm text-slate-600 transition hover:bg-slate-50 hover:text-slate-950"
                                  >
                                    <span className="material-symbols-rounded text-[15px] leading-none align-middle mr-1">{rule.status === "disabled" ? "play_arrow" : "pause"}</span>
                                    {rule.status === "disabled" ? "Resume rule" : "Pause rule"}
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => void deleteRule(rule.ruleId)}
                                    className="flex w-full rounded-xl px-3 py-2 text-sm text-rose-600 transition hover:bg-rose-50"
                                  >
                                    Delete rule
                                  </button>
                                </div>
                              ) : null}
                            </div>
                          </div>
                        </div>
                      </div>
                    ))
                ) : (
                  <div className="md:col-span-2 xl:col-span-3">
                    <EmptyPanel text="No rules available for this selection." />
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="rounded-[26px] border border-slate-200 bg-white p-6">
                {selectedRule ? (
                  <>
                    <button
                      type="button"
                      onClick={() => setRuleView("library")}
                      className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium text-slate-600"
                    >
                      <span className="material-symbols-rounded text-[18px] leading-none">arrow_back</span>
                      <span>Back to library</span>
                    </button>

                    <div className="mt-5 flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">
                          {selectedRule.tool}
                        </p>
                        <h3 className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-slate-950">
                          {selectedRule.title}
                        </h3>
                        <p className="mt-2 max-w-3xl text-sm text-slate-500">
                          {selectedRule.description}
                        </p>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        <span
                          className={`rounded-full border px-2.5 py-1 text-[11px] font-medium ${severityBadge(
                            selectedRule.severity
                          )}`}
                        >
                          {selectedRule.severity}
                        </span>
                        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-medium text-slate-500">
                          {sourceLabel(selectedRule.ruleId)}
                        </span>
                        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-medium text-slate-500">
                          {ruleFrequencyLabel(selectedRule)}
                        </span>
                        <span className={`rounded-full border px-2.5 py-1 text-[11px] font-medium ${
                          selectedRule.status === "disabled"
                            ? "border-amber-200 bg-amber-50 text-amber-700"
                            : selectedRule.status === "approved"
                              ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                              : "border-slate-200 bg-slate-50 text-slate-500"
                        }`}>
                          {selectedRule.status === "disabled" ? "⏸ paused" : selectedRule.status}
                        </span>
                        <div className="relative">
                          <button
                            type="button"
                            onClick={() =>
                              setRuleMenuOpenId((current) =>
                                current === selectedRule.ruleId ? null : selectedRule.ruleId
                              )
                            }
                            className="rounded-full border border-slate-200 bg-white p-2 text-slate-500 transition hover:border-slate-300 hover:text-slate-900"
                            aria-label={`Manage ${selectedRule.title}`}
                          >
                            <GearIcon />
                          </button>
                          {ruleMenuOpenId === selectedRule.ruleId ? (
                            <div className="absolute right-0 top-12 z-20 w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_16px_40px_rgba(15,23,42,0.08)]">
                              <p className="px-3 py-2 text-[11px] font-medium uppercase tracking-[0.18em] text-slate-400">
                                Frequency
                              </p>
                              <div className="space-y-1">
                                {ruleFrequencies.map((frequency) => (
                                  <button
                                    key={frequency}
                                    type="button"
                                    onClick={() =>
                                      void updateRule(selectedRule.ruleId, { frequency })
                                    }
                                    className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-sm transition ${
                                      ruleFrequencyLabel(selectedRule) === frequency
                                        ? "bg-slate-900 text-white"
                                        : "text-slate-600 hover:bg-slate-50 hover:text-slate-950"
                                    }`}
                                  >
                                    <span>{frequency}</span>
                                  </button>
                                ))}
                              </div>
                              <div className="my-2 h-px bg-slate-100" />
                              <button
                                type="button"
                                onClick={() =>
                                  void updateRule(selectedRule.ruleId, {
                                    status:
                                      selectedRule.status === "disabled" ? "approved" : "disabled",
                                  })
                                }
                                className="flex w-full rounded-xl px-3 py-2 text-sm text-slate-600 transition hover:bg-slate-50 hover:text-slate-950"
                              >
                                {selectedRule.status === "disabled" ? "Resume rule" : "Pause rule"}
                              </button>
                              <button
                                type="button"
                                onClick={() => void deleteRule(selectedRule.ruleId)}
                                className="flex w-full rounded-xl px-3 py-2 text-sm text-rose-600 transition hover:bg-rose-50"
                              >
                                Delete rule
                              </button>
                            </div>
                          ) : null}
                        </div>
                      </div>
                    </div>

                    {/* Generation source badge */}
                    {(() => {
                      const by = (selectedRule.generatedDsl as Record<string, unknown>)?.generatedBy as string | undefined;
                      if (!by) return null;
                      const isLlm = by !== "heuristic" && by !== "system" && by !== "watchdog" && by !== "log-monitor" && by !== "qa-agent";
                      return (
                        <div className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-medium text-slate-500">
                          <span className={`h-1.5 w-1.5 rounded-full ${isLlm ? "bg-cyan-400" : "bg-slate-400"}`} />
                          Generated by {isLlm ? <span className="text-cyan-700">{by}</span> : by}
                        </div>
                      );
                    })()}

                    <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                      {[
                        { label: "Metric", value: String(selectedRule.conditions[0]?.threshold ?? "custom") },
                        { label: "Target scope", value: selectedRule.targetScope },
                        { label: "Frequency", value: ruleFrequencyLabel(selectedRule) },
                        { label: "Last updated", value: formatTimestamp(selectedRule.updatedAt) },
                      ].map(({ label, value }) => (
                        <div key={label} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                          <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-slate-400">{label}</p>
                          <p className="mt-2 text-sm font-semibold text-slate-800">{value}</p>
                        </div>
                      ))}
                    </div>

                    <div className="mt-4 rounded-2xl border border-slate-200 bg-[#0f1117] p-4">
                      <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-slate-500 mb-3">
                        Command preview
                      </p>
                      <pre className="font-mono text-xs leading-6 text-emerald-400 whitespace-pre-wrap break-all">
                        {ruleCommandPreview(selectedRule)}
                      </pre>
                    </div>

                    {selectedRule.draft.evidence.length ? (
                      <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                        <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-slate-400 mb-3">
                          Why this check
                        </p>
                        <div className="space-y-2">
                          {selectedRule.draft.evidence.slice(0, 3).map((item) => (
                            <div key={item} className="flex items-start gap-2.5 text-sm text-slate-600">
                              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
                              <p>{item}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    ) : null}

                    {selectedRule.status === "draft" ? (
                      <div className="mt-5 flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                        <span className="material-symbols-rounded text-[20px] text-amber-500 leading-none">warning</span>
                        <p className="flex-1 text-sm text-slate-600">This rule is in draft — review and approve it to activate monitoring.</p>
                        <button
                          type="button"
                          onClick={() => void approveRule(selectedRule.ruleId)}
                          className="shrink-0 rounded-full border border-indigo-600 bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:brightness-105"
                        >
                          Approve rule
                        </button>
                      </div>
                    ) : null}
                  </>
                ) : (
                  <EmptyPanel text="Select a rule to inspect its details." />
                )}
              </div>

              <div className="rounded-[26px] border border-slate-200 bg-white p-6">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="text-lg font-semibold text-slate-950">Runs</p>
                    <p className="mt-1 text-sm text-slate-500">
                      {selectedRule
                        ? "Recent run history for the selected rule"
                        : "Select a rule to inspect its runs"}
                    </p>
                  </div>
                  {selectedRuleRuns.length ? (
                    <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-600">
                      {selectedRuleRuns.length} total
                    </span>
                  ) : null}
                </div>

                <div className="mt-4 space-y-2">
                  {selectedRuleRuns.length ? (
                    selectedRuleRuns.map((run) => (
                      <div
                        key={run.runId}
                        className="rounded-2xl border border-slate-200 bg-white p-4 transition hover:border-slate-300"
                      >
                        <div className="flex items-center justify-between gap-3">
                          <div className="flex items-center gap-3">
                            <span className={`h-2 w-2 rounded-full shrink-0 ${
                              run.status === "fail" ? "bg-rose-400" : run.status === "warn" ? "bg-amber-400" : "bg-emerald-400"
                            }`} />
                            <div>
                              <p className="text-sm font-semibold text-slate-900">
                                {formatTimestamp(run.executedAt)}
                              </p>
                              <p className="mt-0.5 text-xs text-slate-400">
                                {run.triggerSource} · {run.adapterId}
                              </p>
                            </div>
                          </div>
                          <div className="flex flex-wrap gap-2">
                            <span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusBadge(run.status)}`}>
                              {run.status}
                            </span>
                            <span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${severityBadge(run.severity)}`}>
                              {run.severity}
                            </span>
                          </div>
                        </div>
                        {summarizeEvidence(run.evidence).length > 0 && (
                          <div className="mt-3 pl-5 space-y-1">
                            {summarizeEvidence(run.evidence).map((item) => (
                              <p key={`${run.runId}-${item}`} className="text-xs text-slate-500 leading-relaxed">{item}</p>
                            ))}
                          </div>
                        )}
                      </div>
                    ))
                  ) : (
                    <EmptyPanel text="No runs recorded yet for this rule." />
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      ) : null}

      {activeSection === "Alerts" ? (
        <div className="space-y-4">
          <div className="rounded-[26px] border border-slate-200 bg-white p-5">
            {/* Header with severity summary */}
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Alert feed</p>
                <p className="mt-1.5 text-xl font-semibold tracking-[-0.03em] text-slate-950">
                  Active issues &amp; escalations
                </p>
                <p className="mt-1 text-sm text-slate-500">
                  {activeTool === "All tools" ? "Your workspace" : activeTool}
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                {(["SEV-1","SEV-2","SEV-3","SEV-4"] as const).map((sev) => {
                  const count = filteredAlerts.filter(a => a.severity === sev && a.status === "open").length;
                  if (!count) return null;
                  return (
                    <span key={sev} className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium ${severityBadge(sev)}`}>
                      <span className={`h-1.5 w-1.5 rounded-full ${severityDot(sev)}`} />
                      {count} {sev}
                    </span>
                  );
                })}
                <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-medium text-slate-500">
                  {filteredAlerts.length} total
                </span>
              </div>
            </div>

            <div className="mt-5 grid gap-3 xl:grid-cols-2">
              {filteredAlerts.length ? (
                filteredAlerts.map((alert) => (
                  <div
                    key={alert.alertId}
                    className={`relative rounded-[20px] border p-5 transition hover:shadow-sm ${severityCard(alert.severity)}`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-start gap-3 min-w-0">
                        {alert.severity === "SEV-1" ? (
                          <span className="relative mt-0.5 flex h-3 w-3 shrink-0">
                            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-rose-300 opacity-70" />
                            <span className="relative inline-flex h-3 w-3 rounded-full bg-rose-400" />
                          </span>
                        ) : (
                          <span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${severityDot(alert.severity)}`} />
                        )}
                        <p className="text-sm font-semibold text-slate-900 leading-snug">{alert.title}</p>
                      </div>
                      <span
                        className={`shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold tracking-wide ${severityBadge(
                          alert.severity
                        )}`}
                      >
                        {alert.severity}
                      </span>
                    </div>

                    <p className="mt-3 pl-[22px] text-sm text-slate-500 leading-relaxed">{alert.detail}</p>

                    <div className="mt-4 pl-[22px] flex flex-wrap items-center justify-between gap-3">
                      <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400">
                        <span>{formatTimestamp(alert.createdAt)}</span>
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${
                          alert.status === "open"
                            ? "border-rose-200 bg-white text-rose-600"
                            : "border-slate-200 bg-white text-slate-500"
                        }`}>
                          {alert.status}
                        </span>
                        {alert.mailDeliveredAt ? (
                          <span className="rounded-full border border-emerald-200 bg-white px-2 py-0.5 text-emerald-600 font-medium">
                            <span className="material-symbols-rounded text-[13px] leading-none align-middle mr-0.5">mail</span> emailed
                          </span>
                        ) : null}
                      </div>
                      <button
                        type="button"
                        onClick={() =>
                          onRemedyAlert?.(
                            alert,
                            filteredRules.find((rule) => rule.ruleId === alert.ruleId)
                          )
                        }
                        className="inline-flex items-center gap-2 rounded-full border border-indigo-600 bg-indigo-600 px-3.5 py-1.5 text-xs font-semibold text-white transition hover:brightness-105 active:brightness-95"
                      >
                        Remedy
                        <span className="material-symbols-rounded text-[15px] leading-none">open_in_new</span>
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="xl:col-span-2">
                  <div className="rounded-[20px] border border-dashed border-slate-200 bg-slate-50/60 p-10 text-center">
                    <span className="material-symbols-rounded text-[40px] text-emerald-400 leading-none mb-2 block">check_circle</span>
                    <p className="text-sm font-medium text-slate-600">All clear — no quality alerts right now.</p>
                    <p className="mt-1 text-xs text-slate-400">Alerts will appear here when rules fire.</p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {showMailModal ? (
            <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/35 p-4 backdrop-blur-sm">
              <div className="w-full max-w-2xl rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.12)]">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-lg font-semibold text-slate-950">Email notifications</p>
                    <p className="mt-1 text-sm text-slate-500">
                      Set recipients and choose which severities should reach them.
                    </p>
                  </div>
                  <button
                    type="button"
                    onClick={() => setShowMailModal(false)}
                    className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-sm text-slate-600"
                  >
                    Close
                  </button>
                </div>

                <div className="mt-5 space-y-4">
                  <label className="block">
                    <span className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">
                      Sender address
                    </span>
                    <input
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-700 outline-none"
                      placeholder="alerts@your-company.com"
                      value={mailForm.sender}
                      onChange={(event) =>
                        setMailForm((current) => ({ ...current, sender: event.target.value }))
                      }
                    />
                  </label>

                  <label className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-600">
                    <input
                      type="checkbox"
                      checked={mailForm.enabled}
                      onChange={(event) =>
                        setMailForm((current) => ({ ...current, enabled: event.target.checked }))
                      }
                    />
                    Enable email alerts
                  </label>

                  <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                    <p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">
                      Recipients
                    </p>

                    <div className="mt-3 flex flex-col gap-3 md:flex-row">
                      <input
                        className="flex-1 rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none"
                        placeholder="team@company.com"
                        value={recipientDraft}
                        onChange={(event) => setRecipientDraft(event.target.value)}
                      />
                      <select
                        className="rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none"
                        value={recipientSeverity}
                        onChange={(event) =>
                          setRecipientSeverity(
                            event.target.value as MailSettings["recipients"][number]["notifyAtOrAbove"]
                          )
                        }
                      >
                        {severityLevels.map((severity) => (
                          <option key={severity} value={severity}>
                            {severity}+
                          </option>
                        ))}
                      </select>
                      <button
                        type="button"
                        onClick={addRecipientPolicy}
                        className="rounded-full border border-slate-900 bg-slate-900 px-4 py-2 text-sm font-medium text-white"
                      >
                        Add
                      </button>
                    </div>

                    <div className="mt-4 space-y-3">
                      {recipientPolicies.length ? (
                        recipientPolicies.map((policy) => (
                          <div
                            key={policy.recipient}
                            className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:flex-row md:items-center md:justify-between"
                          >
                            <div>
                              <p className="text-sm font-medium text-slate-900">{policy.recipient}</p>
                              <p className="mt-1 text-xs text-slate-500">
                                Notify when severity is {policy.notifyAtOrAbove} or higher
                              </p>
                            </div>
                            <div className="flex items-center gap-2">
                              <select
                                className="rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-700 outline-none"
                                value={policy.notifyAtOrAbove}
                                onChange={(event) =>
                                  updateRecipientPolicy(
                                    policy.recipient,
                                    event.target.value as MailSettings["recipients"][number]["notifyAtOrAbove"]
                                  )
                                }
                              >
                                {severityLevels.map((severity) => (
                                  <option key={severity} value={severity}>
                                    {severity}+
                                  </option>
                                ))}
                              </select>
                              <button
                                type="button"
                                onClick={() => removeRecipientPolicy(policy.recipient)}
                                className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600"
                              >
                                Remove
                              </button>
                            </div>
                          </div>
                        ))
                      ) : (
                        <EmptyPanel text="No recipients configured yet. Add a team or on-call email to start routing alerts." />
                      )}
                    </div>
                  </div>

                  <div className="flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => setShowMailModal(false)}
                      className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-600"
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={async () => {
                        await saveMail();
                        setShowMailModal(false);
                      }}
                      className="rounded-full border border-slate-900 bg-slate-900 px-4 py-2 text-sm font-medium text-white"
                    >
                      Save recipients
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ) : null}
        </div>
      ) : null}

    </div>
  );
}
